# coding: utf-8

"""
    GeoWebCache Bounds

    A RESTful interface through which get the bounds of a given layer based on srs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gwc_bounds_api import GwcBoundsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGwcBoundsApi(unittest.TestCase):
    """GwcBoundsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.gwc_bounds_api.GwcBoundsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bounds_get(self):
        """Test case for bounds_get

        Returns the bounds for a layer based on srs.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
