# coding: utf-8

# flake8: noqa

"""
    OWS Services

    An OWS service refers to any of the OGC services that GeoServer supports, such as WFS, WMS, and WCS. These endpoints controls the settings of these services.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.ows_services_api import OWSServicesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.wcs_info import WCSInfo
from swagger_client.models.wfs_info import WFSInfo
from swagger_client.models.wfs_info_gml import WFSInfoGml
from swagger_client.models.wfs_info_gml_entry import WFSInfoGmlEntry
from swagger_client.models.wfs_info_gml_gml import WFSInfoGmlGml
from swagger_client.models.wfs_info_metadata_link import WFSInfoMetadataLink
from swagger_client.models.wms_info import WMSInfo
from swagger_client.models.wms_info_metadata_link import WMSInfoMetadataLink
from swagger_client.models.wms_info_versions import WMSInfoVersions
from swagger_client.models.wms_info_watermark import WMSInfoWatermark
from swagger_client.models.wmts_info import WMTSInfo
