# coding: utf-8

"""
    GeoWebCache Seeding and Truncating

    A layer is a published resource (feature type or coverage).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.gwc_seed_api import GwcSeedApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGwcSeedApi(unittest.TestCase):
    """GwcSeedApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.gwc_seed_api.GwcSeedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_layer_seed_get(self):
        """Test case for layer_seed_get

        Query's the currently running GWC task for a given layer  # noqa: E501
        """
        pass

    def test_layer_seed_post(self):
        """Test case for layer_seed_post

        Issue a seed, reseed or truncate task request  # noqa: E501
        """
        pass

    def test_seed_get(self):
        """Test case for seed_get

        Query's currently running GWC task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
