# coding: utf-8

# flake8: noqa
"""
    GeoServer monitoring requests

    Request provides details about OWS and REST requests that GeoServer has handled  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.request import Request
from swagger_client.models.request_list import RequestList
