# coding: utf-8

"""
    GeoServer XSLT transforms

    A transform contains a style sheet that can be used to generate a new textual output format of user choosing for WFS  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transforms_api import TransformsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransformsApi(unittest.TestCase):
    """TransformsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transforms_api.TransformsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tranform(self):
        """Test case for delete_tranform

        Delete transformation  # noqa: E501
        """
        pass

    def test_delete_transform(self):
        """Test case for delete_transform

        """
        pass

    def test_get_transform(self):
        """Test case for get_transform

        Retrieve a transformation.  # noqa: E501
        """
        pass

    def test_get_transforms(self):
        """Test case for get_transforms

        List available transformations.  # noqa: E501
        """
        pass

    def test_post_tranform(self):
        """Test case for post_tranform

        """
        pass

    def test_post_transform(self):
        """Test case for post_transform

        Add a new transform  # noqa: E501
        """
        pass

    def test_put_tranform(self):
        """Test case for put_tranform

        Modify a single transform  # noqa: E501
        """
        pass

    def test_put_transform(self):
        """Test case for put_transform

        """
        pass


if __name__ == '__main__':
    unittest.main()
