# coding: utf-8

"""
    GeoServer WMTS Store Layers

    A WMTS store is a store whose source is a remote WMTS service. Also known as \"Cascading WMTS\". A WMTS store layer is a layer from this store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wmts_store_layers_list import WMTSStoreLayersList  # noqa: E501
from swagger_client.rest import ApiException


class TestWMTSStoreLayersList(unittest.TestCase):
    """WMTSStoreLayersList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWMTSStoreLayersList(self):
        """Test WMTSStoreLayersList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wmts_store_layers_list.WMTSStoreLayersList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
