# coding: utf-8

"""
    GeoServer Importer Extension - Data

    The Importer extension gives a GeoServer administrator an alternate, more-streamlined method for uploading and configuring new layers. The data endpoint controls uploading layer data to specific import jobs. The importer extension is an optional install and may not be available on all deployments of GeoServer  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.importer_data_api import ImporterDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImporterDataApi(unittest.TestCase):
    """ImporterDataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.importer_data_api.ImporterDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_import_data_file(self):
        """Test case for delete_import_data_file

        Remove a specific file with id {filename} from the import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass

    def test_delete_task_data_file(self):
        """Test case for delete_task_data_file

        Remove a specific file with id {filename} from the task with id {taskId} within import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass

    def test_get_data(self):
        """Test case for get_data

        Retrieve the database connection parameters for an import with id {importId}. Only applies to database imports.  # noqa: E501
        """
        pass

    def test_get_data_file(self):
        """Test case for get_data_file

        Retrieve information about the file with id {fileId} from the data of an import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass

    def test_get_data_files(self):
        """Test case for get_data_files

        Retrieve the list of files for an import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass

    def test_get_task_data(self):
        """Test case for get_task_data

        Retrieve the table description for a task with id {taskId} within import with id {importId}. Only applies to database imports.  # noqa: E501
        """
        pass

    def test_get_task_data_file(self):
        """Test case for get_task_data_file

        Retrieve information about the file with id {fileId} from the data of a task with id {taskId} within import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass

    def test_get_task_data_files(self):
        """Test case for get_task_data_files

        Retrieve the list of files for a task with id {taskId} within import with id {importId}. Only applies to file/directory imports.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
