# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.workspaces_api import WorkspacesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.workspaces_api.WorkspacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_workspace(self):
        """Test case for delete_workspace

        """
        pass

    def test_delete_workspaces(self):
        """Test case for delete_workspaces

        """
        pass

    def test_get_workspace(self):
        """Test case for get_workspace

        Retrieve a layer group  # noqa: E501
        """
        pass

    def test_get_workspaces(self):
        """Test case for get_workspaces

        Get a list of workspaces  # noqa: E501
        """
        pass

    def test_post_workspace(self):
        """Test case for post_workspace

        """
        pass

    def test_post_workspaces(self):
        """Test case for post_workspaces

        add a new workspace to GeoServer  # noqa: E501
        """
        pass

    def test_put_workspace(self):
        """Test case for put_workspace

        Update a workspace  # noqa: E501
        """
        pass

    def test_put_workspaces(self):
        """Test case for put_workspaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
