# coding: utf-8

"""
    GeoWebCache GridSets

    A Grid Set is a set of tile grids associated with a coordinate reference system.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.grid_set_scale_names import GridSetScaleNames  # noqa: E501
from swagger_client.rest import ApiException


class TestGridSetScaleNames(unittest.TestCase):
    """GridSetScaleNames unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridSetScaleNames(self):
        """Test GridSetScaleNames"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grid_set_scale_names.GridSetScaleNames()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
