# coding: utf-8

"""
    GeoWebCache Global

    Global configuration for the GeoWebCache server  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_provider import ServiceProvider  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceProvider(unittest.TestCase):
    """ServiceProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceProvider(self):
        """Test ServiceProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_provider.ServiceProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
