# coding: utf-8

# flake8: noqa

"""
    GeoServer Resources

    A resource is any item in the data directory that does not represent configuration. Typical resources include styles and icons.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.resource_api import ResourceApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.resource_directory import ResourceDirectory
from swagger_client.models.resource_directory_children import ResourceDirectoryChildren
from swagger_client.models.resource_directory_children_child import ResourceDirectoryChildrenChild
from swagger_client.models.resource_directory_children_link import ResourceDirectoryChildrenLink
from swagger_client.models.resource_metadata import ResourceMetadata
from swagger_client.models.resource_metadata_parent import ResourceMetadataParent
from swagger_client.models.resource_metadata_parent_link import ResourceMetadataParentLink
