# coding: utf-8

"""
    GeoServer Feature Types

    A feature type is a vector based spatial resource or data set that originates from a data store. In some cases, such as with a shapefile, a feature type has a one-to-one relationship with its data store. In other cases, such as PostGIS, the relationship of feature type to data store is many-to-one, feature types corresponding to a table in the database.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.feature_types_api import FeatureTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeatureTypesApi(unittest.TestCase):
    """FeatureTypesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.feature_types_api.FeatureTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_feature_type(self):
        """Test case for delete_feature_type

        """
        pass

    def test_delete_feature_type_0(self):
        """Test case for delete_feature_type_0

        """
        pass

    def test_delete_feature_types(self):
        """Test case for delete_feature_types

        """
        pass

    def test_delete_feature_types_0(self):
        """Test case for delete_feature_types_0

        """
        pass

    def test_get_feature_type(self):
        """Test case for get_feature_type

        """
        pass

    def test_get_feature_type_0(self):
        """Test case for get_feature_type_0

        """
        pass

    def test_get_feature_types(self):
        """Test case for get_feature_types

        """
        pass

    def test_get_feature_types_0(self):
        """Test case for get_feature_types_0

        """
        pass

    def test_post_feature_type(self):
        """Test case for post_feature_type

        """
        pass

    def test_post_feature_type_0(self):
        """Test case for post_feature_type_0

        """
        pass

    def test_post_feature_type_reset(self):
        """Test case for post_feature_type_reset

        Reset the caches related to this specific feature type  # noqa: E501
        """
        pass

    def test_post_feature_type_reset_0(self):
        """Test case for post_feature_type_reset_0

        Reset the caches related to this specific feature type  # noqa: E501
        """
        pass

    def test_post_feature_types(self):
        """Test case for post_feature_types

        """
        pass

    def test_post_feature_types_0(self):
        """Test case for post_feature_types_0

        """
        pass

    def test_put_feature_type(self):
        """Test case for put_feature_type

        """
        pass

    def test_put_feature_type_0(self):
        """Test case for put_feature_type_0

        """
        pass

    def test_put_feature_type_reset(self):
        """Test case for put_feature_type_reset

        Reset the caches related to this specific feature type.  # noqa: E501
        """
        pass

    def test_put_feature_type_reset_0(self):
        """Test case for put_feature_type_reset_0

        Reset the caches related to this specific feature type.  # noqa: E501
        """
        pass

    def test_put_feature_types(self):
        """Test case for put_feature_types

        """
        pass

    def test_put_feature_types_0(self):
        """Test case for put_feature_types_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
