# coding: utf-8

# flake8: noqa

"""
    GeoServer Feature Types

    A feature type is a vector based spatial resource or data set that originates from a data store. In some cases, such as with a shapefile, a feature type has a one-to-one relationship with its data store. In other cases, such as PostGIS, the relationship of feature type to data store is many-to-one, feature types corresponding to a table in the database.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.feature_types_api import FeatureTypesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.feature_type_info import FeatureTypeInfo
from swagger_client.models.feature_type_info_attributes import FeatureTypeInfoAttributes
from swagger_client.models.feature_type_info_attributes_attribute import FeatureTypeInfoAttributesAttribute
from swagger_client.models.feature_type_info_data_links import FeatureTypeInfoDataLinks
from swagger_client.models.feature_type_info_data_links_metadata_link import FeatureTypeInfoDataLinksMetadataLink
from swagger_client.models.feature_type_info_keywords import FeatureTypeInfoKeywords
from swagger_client.models.feature_type_info_lat_lon_bounding_box import FeatureTypeInfoLatLonBoundingBox
from swagger_client.models.feature_type_info_metadatalinks import FeatureTypeInfoMetadatalinks
from swagger_client.models.feature_type_info_metadatalinks_metadata_link import FeatureTypeInfoMetadatalinksMetadataLink
from swagger_client.models.feature_type_info_namespace import FeatureTypeInfoNamespace
from swagger_client.models.feature_type_info_native_bounding_box import FeatureTypeInfoNativeBoundingBox
from swagger_client.models.feature_type_info_response_srs import FeatureTypeInfoResponseSRS
from swagger_client.models.feature_type_info_store import FeatureTypeInfoStore
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response200_feature_types import InlineResponse200FeatureTypes
from swagger_client.models.inline_response200_feature_types_feature_type import InlineResponse200FeatureTypesFeatureType
from swagger_client.models.metadata_entry import MetadataEntry
