# coding: utf-8

"""
    GeoServer Importer Extension - Main

    The Importer extension gives a GeoServer administrator an alternate, more-streamlined method for uploading and configuring new layers. The main endpoint manages individual import jobs. The importer extension is an optional install and may not be available on all deployments of GeoServer  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class DataFormatTransform(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'href': 'str',
        'field': 'str',
        'format': 'str'
    }

    attribute_map = {
        'type': 'type',
        'href': 'href',
        'field': 'field',
        'format': 'format'
    }

    def __init__(self, type=None, href=None, field=None, format=None, _configuration=None):  # noqa: E501
        """DataFormatTransform - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._type = None
        self._href = None
        self._field = None
        self._format = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if href is not None:
            self.href = href
        if field is not None:
            self.field = field
        if format is not None:
            self.format = format

    @property
    def type(self):
        """Gets the type of this DataFormatTransform.  # noqa: E501

        \"DataFormatTransform\"  # noqa: E501

        :return: The type of this DataFormatTransform.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DataFormatTransform.

        \"DataFormatTransform\"  # noqa: E501

        :param type: The type of this DataFormatTransform.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def href(self):
        """Gets the href of this DataFormatTransform.  # noqa: E501

        URL to the transform endpoint  # noqa: E501

        :return: The href of this DataFormatTransform.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this DataFormatTransform.

        URL to the transform endpoint  # noqa: E501

        :param href: The href of this DataFormatTransform.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def field(self):
        """Gets the field of this DataFormatTransform.  # noqa: E501

        The field to apply the transform to  # noqa: E501

        :return: The field of this DataFormatTransform.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this DataFormatTransform.

        The field to apply the transform to  # noqa: E501

        :param field: The field of this DataFormatTransform.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def format(self):
        """Gets the format of this DataFormatTransform.  # noqa: E501

        A date parsing pattern, setup using the Java SimpleDateFormat syntax. In case it's missing, a number of built-in formats will be tried instead (short and full ISO date formats, dates without any separators).  # noqa: E501

        :return: The format of this DataFormatTransform.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this DataFormatTransform.

        A date parsing pattern, setup using the Java SimpleDateFormat syntax. In case it's missing, a number of built-in formats will be tried instead (short and full ISO date formats, dates without any separators).  # noqa: E501

        :param format: The format of this DataFormatTransform.  # noqa: E501
        :type: str
        """

        self._format = format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataFormatTransform, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataFormatTransform):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataFormatTransform):
            return True

        return self.to_dict() != other.to_dict()
