# coding: utf-8

# flake8: noqa
"""
    GeoServer Layer Groups

    A layer group is a group of layers that can be referenced as a single layer as part of a WMS request. A layer group can also be used as a container for layers.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.layergroup import Layergroup
from swagger_client.models.layergroup_bounds import LayergroupBounds
from swagger_client.models.layergroup_keywords import LayergroupKeywords
from swagger_client.models.layergroup_metadata_link import LayergroupMetadataLink
from swagger_client.models.layergroup_publishables import LayergroupPublishables
from swagger_client.models.layergroup_published import LayergroupPublished
from swagger_client.models.layergroup_response import LayergroupResponse
from swagger_client.models.layergroup_style import LayergroupStyle
from swagger_client.models.layergroup_styles import LayergroupStyles
from swagger_client.models.layergroup_workspace import LayergroupWorkspace
from swagger_client.models.layergroups import Layergroups
