# coding: utf-8

# flake8: noqa
"""
    GeoWebCache Memory Cache Statistics

    A response contains memory cache statistics  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
