# coding: utf-8

"""
    GeoServer Parameter Extractor

    A parameter extractor rule allows specific request parameters as URL path fragments instead of using the query string. A echo parameter makes sure that certain URL paratemers are added to the capabilities documents backlinks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.echo_parameter_list_item import EchoParameterListItem  # noqa: E501
from swagger_client.rest import ApiException


class TestEchoParameterListItem(unittest.TestCase):
    """EchoParameterListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoParameterListItem(self):
        """Test EchoParameterListItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.echo_parameter_list_item.EchoParameterListItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
