# coding: utf-8

"""
    GeoServer WMS Store Layers

    A WMS store is a store whose source is another WMS. Also known as \"Cascading WMS\" or \"External WMS\". A WMS store layer is a layer from this store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wms_store_layer_info_namespace import WMSStoreLayerInfoNamespace  # noqa: E501
from swagger_client.rest import ApiException


class TestWMSStoreLayerInfoNamespace(unittest.TestCase):
    """WMSStoreLayerInfoNamespace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWMSStoreLayerInfoNamespace(self):
        """Test WMSStoreLayerInfoNamespace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wms_store_layer_info_namespace.WMSStoreLayerInfoNamespace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
