# coding: utf-8

"""
    GeoServer Resources

    A resource is any item in the data directory that does not represent configuration. Typical resources include styles and icons.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resource_directory import ResourceDirectory  # noqa: E501
from swagger_client.rest import ApiException


class TestResourceDirectory(unittest.TestCase):
    """ResourceDirectory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceDirectory(self):
        """Test ResourceDirectory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resource_directory.ResourceDirectory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
