# coding: utf-8

"""
    GeoServer WMTS Stores

    A WMTS store is a store whose source is a remote WMTS. Also known as \"Cascading WMTS\".  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wmts_stores_api import WMTSStoresApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWMTSStoresApi(unittest.TestCase):
    """WMTSStoresApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wmts_stores_api.WMTSStoresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_wmts_store(self):
        """Test case for delete_wmts_store

        Delete WMTS store  # noqa: E501
        """
        pass

    def test_delete_wmts_stores(self):
        """Test case for delete_wmts_stores

        """
        pass

    def test_get_wmts_store(self):
        """Test case for get_wmts_store

        Retrieve a WMTS store in a given workspace  # noqa: E501
        """
        pass

    def test_get_wmts_stores(self):
        """Test case for get_wmts_stores

        Get a list of WMTS stores  # noqa: E501
        """
        pass

    def test_post_wmts_store(self):
        """Test case for post_wmts_store

        """
        pass

    def test_post_wmts_stores(self):
        """Test case for post_wmts_stores

        Add a new WMTS store  # noqa: E501
        """
        pass

    def test_put_wmts_store(self):
        """Test case for put_wmts_store

        Modify a single WMTS store.  # noqa: E501
        """
        pass

    def test_put_wmts_stores(self):
        """Test case for put_wmts_stores

        """
        pass


if __name__ == '__main__':
    unittest.main()
