# coding: utf-8

# flake8: noqa

"""
    GeoServer CoverageStores

    A coverage store describes how access a raster data source.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.coverage_stores_api import CoverageStoresApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.coverage_store_info import CoverageStoreInfo
from swagger_client.models.coverage_store_info_coverages import CoverageStoreInfoCoverages
from swagger_client.models.coverage_store_info_workspace import CoverageStoreInfoWorkspace
from swagger_client.models.coverage_store_list import CoverageStoreList
from swagger_client.models.coverage_store_list_item import CoverageStoreListItem
